### ISSUE TITLE
card text issues

### ISSUE THREAD

**Issue by abdullahtariq1171** [iterative/blog#61] opened 2020-01-08 07:05 UTC
### 1) text overlap
![text overlap](https://monosnap.com/image/jThEutHTShsywBhPcOkHpHaaOYr9fN)

### 2) text hidden
![ text hidden](https://monosnap.com/image/pP8DP6tqpuVXcszgUMCs0sEskLBZU3)

**Comment by shcheklein** [comment] 2020-01-08 17:11
@abdullahtariq1171 good catch! do you mind sharing what browser do you run it on? I was trying to reproduce and I can't so far.

**Comment by abdullahtariq1171** [comment] 2020-01-08 18:04
@shcheklein 
- Firefox 71.0
- Chrome 79.0.3945.88

**Comment by shcheklein** [comment] 2020-01-08 18:39
@abdullahtariq1171 but on the second screenshot text does not overlap for the same page, how is it possible?

**Comment by abdullahtariq1171** [comment] 2020-01-08 19:00
@shcheklein nah both are different issues. I put both in one issue only because they are related to card. 

Here is how we can reproduce https://monosnap.com/file/lCcyrGgj2EFil4pacIRUgNDTwgWkhK

**Comment by shcheklein** [comment] 2020-01-08 19:10
k, I see. It's not clear that width was the key to reproduce. Thanks!

**Comment by fadilmamedov** [comment] 2020-01-09 17:51
@shcheklein I will take care of this one

**Comment by shcheklein** [comment] 2020-01-09 17:51
@fadilmamedov thanks! 👍

**Comment by fadilmamedov** [comment] 2020-01-09 18:30
@shcheklein regarding the second part of the issue. I don't think that dividing the second row into two rows would look better. What about shrinking the padding of the description and meta sections in the card to 20px? Then it would look like:

<img width="723" alt="Screenshot 2020-01-09 at 21 28 17" src="https://user-images.githubusercontent.com/3175922/72094230-fb882980-3326-11ea-90df-deb75423b550.png">

In that case it first of all looks better and additionally meta information can be placed into one single row.

**Comment by shcheklein** [comment] 2020-01-09 18:32
@fadilmamedov works for me.

**Comment by shcheklein** [comment] 2020-01-29 19:37
Agreed with @cosmn to take a holistic look at how card is structured.

**Comment by cosmn** [comment] 2020-01-30 22:35
@shcheklein Latest commits and PR should close this issue.
For a feed card refactoring, we should open a new issue, and a new branch to go with that. Either way, it wont have a significant visual impact, just the a new CSS approach.

**Comment by shcheklein** [comment] 2020-01-30 22:37
Fixed by #89

**Closed by shcheklein** 2020-01-30 22:37 UTC
Labels: blog, bug, priority-p1
